version: "2"
run:
  issues-exit-code: 1
  tests: true
linters:
  default: none
  enable:
    - contextcheck
    - durationcheck
    - errcheck
    - errname
    - exhaustive
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nilerr
    - nilnil
    - prealloc
    - revive
    - staticcheck
    - unused
    - usestdlibvars
    # - wsl # excluded from linters list because produces too many noise
  settings:
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      ignore-tests: true
    misspell:
      locale: US
      ignore-rules:
        - GitLab
    revive:
      rules:
        - name: use-any
        - name: string-format
          arguments:
            - - fmt.Errorf[0]
              - /^[^A-Z].*$/
              - error messages must not start with capital letter
            - - log.Printf[0]
              - /^[^a-z].*$/
              - log messages must not start with lowercase letter
          severity: error
          disabled: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
