// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocktopology

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tarantool/go-vshard-router/v2"
)

// NewTopologyController creates a new instance of TopologyController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTopologyController(t interface {
	mock.TestingT
	Cleanup(func())
}) *TopologyController {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &TopologyController{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// TopologyController is an autogenerated mock type for the TopologyController type
type TopologyController struct {
	mock.Mock
}

type TopologyController_Expecter struct {
	mock *mock.Mock
}

func (_m *TopologyController) EXPECT() *TopologyController_Expecter {
	return &TopologyController_Expecter{mock: &_m.Mock}
}

// AddInstance provides a mock function for the type TopologyController
func (_mock *TopologyController) AddInstance(ctx context.Context, rsName string, info vshard_router.InstanceInfo) error {
	ret := _mock.Called(ctx, rsName, info)

	if len(ret) == 0 {
		panic("no return value specified for AddInstance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, vshard_router.InstanceInfo) error); ok {
		r0 = returnFunc(ctx, rsName, info)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TopologyController_AddInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddInstance'
type TopologyController_AddInstance_Call struct {
	*mock.Call
}

// AddInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - rsName string
//   - info vshard_router.InstanceInfo
func (_e *TopologyController_Expecter) AddInstance(ctx any, rsName any, info any) *TopologyController_AddInstance_Call {
	return &TopologyController_AddInstance_Call{Call: _e.mock.On("AddInstance", ctx, rsName, info)}
}

func (_c *TopologyController_AddInstance_Call) Run(run func(ctx context.Context, rsName string, info vshard_router.InstanceInfo)) *TopologyController_AddInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 vshard_router.InstanceInfo
		if args[2] != nil {
			arg2 = args[2].(vshard_router.InstanceInfo)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TopologyController_AddInstance_Call) Return(err error) *TopologyController_AddInstance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TopologyController_AddInstance_Call) RunAndReturn(run func(ctx context.Context, rsName string, info vshard_router.InstanceInfo) error) *TopologyController_AddInstance_Call {
	_c.Call.Return(run)
	return _c
}

// AddReplicaset provides a mock function for the type TopologyController
func (_mock *TopologyController) AddReplicaset(ctx context.Context, rsInfo vshard_router.ReplicasetInfo, instances []vshard_router.InstanceInfo) error {
	ret := _mock.Called(ctx, rsInfo, instances)

	if len(ret) == 0 {
		panic("no return value specified for AddReplicaset")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, vshard_router.ReplicasetInfo, []vshard_router.InstanceInfo) error); ok {
		r0 = returnFunc(ctx, rsInfo, instances)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TopologyController_AddReplicaset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddReplicaset'
type TopologyController_AddReplicaset_Call struct {
	*mock.Call
}

// AddReplicaset is a helper method to define mock.On call
//   - ctx context.Context
//   - rsInfo vshard_router.ReplicasetInfo
//   - instances []vshard_router.InstanceInfo
func (_e *TopologyController_Expecter) AddReplicaset(ctx any, rsInfo any, instances any) *TopologyController_AddReplicaset_Call {
	return &TopologyController_AddReplicaset_Call{Call: _e.mock.On("AddReplicaset", ctx, rsInfo, instances)}
}

func (_c *TopologyController_AddReplicaset_Call) Run(run func(ctx context.Context, rsInfo vshard_router.ReplicasetInfo, instances []vshard_router.InstanceInfo)) *TopologyController_AddReplicaset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 vshard_router.ReplicasetInfo
		if args[1] != nil {
			arg1 = args[1].(vshard_router.ReplicasetInfo)
		}
		var arg2 []vshard_router.InstanceInfo
		if args[2] != nil {
			arg2 = args[2].([]vshard_router.InstanceInfo)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TopologyController_AddReplicaset_Call) Return(err error) *TopologyController_AddReplicaset_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TopologyController_AddReplicaset_Call) RunAndReturn(run func(ctx context.Context, rsInfo vshard_router.ReplicasetInfo, instances []vshard_router.InstanceInfo) error) *TopologyController_AddReplicaset_Call {
	_c.Call.Return(run)
	return _c
}

// AddReplicasets provides a mock function for the type TopologyController
func (_mock *TopologyController) AddReplicasets(ctx context.Context, replicasets map[vshard_router.ReplicasetInfo][]vshard_router.InstanceInfo) error {
	ret := _mock.Called(ctx, replicasets)

	if len(ret) == 0 {
		panic("no return value specified for AddReplicasets")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[vshard_router.ReplicasetInfo][]vshard_router.InstanceInfo) error); ok {
		r0 = returnFunc(ctx, replicasets)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TopologyController_AddReplicasets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddReplicasets'
type TopologyController_AddReplicasets_Call struct {
	*mock.Call
}

// AddReplicasets is a helper method to define mock.On call
//   - ctx context.Context
//   - replicasets map[vshard_router.ReplicasetInfo][]vshard_router.InstanceInfo
func (_e *TopologyController_Expecter) AddReplicasets(ctx any, replicasets any) *TopologyController_AddReplicasets_Call {
	return &TopologyController_AddReplicasets_Call{Call: _e.mock.On("AddReplicasets", ctx, replicasets)}
}

func (_c *TopologyController_AddReplicasets_Call) Run(run func(ctx context.Context, replicasets map[vshard_router.ReplicasetInfo][]vshard_router.InstanceInfo)) *TopologyController_AddReplicasets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[vshard_router.ReplicasetInfo][]vshard_router.InstanceInfo
		if args[1] != nil {
			arg1 = args[1].(map[vshard_router.ReplicasetInfo][]vshard_router.InstanceInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TopologyController_AddReplicasets_Call) Return(err error) *TopologyController_AddReplicasets_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TopologyController_AddReplicasets_Call) RunAndReturn(run func(ctx context.Context, replicasets map[vshard_router.ReplicasetInfo][]vshard_router.InstanceInfo) error) *TopologyController_AddReplicasets_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveInstance provides a mock function for the type TopologyController
func (_mock *TopologyController) RemoveInstance(ctx context.Context, rsName string, instanceName string) error {
	ret := _mock.Called(ctx, rsName, instanceName)

	if len(ret) == 0 {
		panic("no return value specified for RemoveInstance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, rsName, instanceName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TopologyController_RemoveInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveInstance'
type TopologyController_RemoveInstance_Call struct {
	*mock.Call
}

// RemoveInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - rsName string
//   - instanceName string
func (_e *TopologyController_Expecter) RemoveInstance(ctx any, rsName any, instanceName any) *TopologyController_RemoveInstance_Call {
	return &TopologyController_RemoveInstance_Call{Call: _e.mock.On("RemoveInstance", ctx, rsName, instanceName)}
}

func (_c *TopologyController_RemoveInstance_Call) Run(run func(ctx context.Context, rsName string, instanceName string)) *TopologyController_RemoveInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TopologyController_RemoveInstance_Call) Return(err error) *TopologyController_RemoveInstance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TopologyController_RemoveInstance_Call) RunAndReturn(run func(ctx context.Context, rsName string, instanceName string) error) *TopologyController_RemoveInstance_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveReplicaset provides a mock function for the type TopologyController
func (_mock *TopologyController) RemoveReplicaset(ctx context.Context, rsName string) []error {
	ret := _mock.Called(ctx, rsName)

	if len(ret) == 0 {
		panic("no return value specified for RemoveReplicaset")
	}

	var r0 []error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []error); ok {
		r0 = returnFunc(ctx, rsName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]error)
		}
	}
	return r0
}

// TopologyController_RemoveReplicaset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveReplicaset'
type TopologyController_RemoveReplicaset_Call struct {
	*mock.Call
}

// RemoveReplicaset is a helper method to define mock.On call
//   - ctx context.Context
//   - rsName string
func (_e *TopologyController_Expecter) RemoveReplicaset(ctx any, rsName any) *TopologyController_RemoveReplicaset_Call {
	return &TopologyController_RemoveReplicaset_Call{Call: _e.mock.On("RemoveReplicaset", ctx, rsName)}
}

func (_c *TopologyController_RemoveReplicaset_Call) Run(run func(ctx context.Context, rsName string)) *TopologyController_RemoveReplicaset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TopologyController_RemoveReplicaset_Call) Return(errs []error) *TopologyController_RemoveReplicaset_Call {
	_c.Call.Return(errs)
	return _c
}

func (_c *TopologyController_RemoveReplicaset_Call) RunAndReturn(run func(ctx context.Context, rsName string) []error) *TopologyController_RemoveReplicaset_Call {
	_c.Call.Return(run)
	return _c
}
