// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocktopology

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	vshard_router "github.com/tarantool/go-vshard-router/v2"
)

// TopologyController is an autogenerated mock type for the TopologyController type
type TopologyController struct {
	mock.Mock
}

// AddInstance provides a mock function with given fields: ctx, rsName, info
func (_m *TopologyController) AddInstance(ctx context.Context, rsName string, info vshard_router.InstanceInfo) error {
	ret := _m.Called(ctx, rsName, info)

	if len(ret) == 0 {
		panic("no return value specified for AddInstance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, vshard_router.InstanceInfo) error); ok {
		r0 = rf(ctx, rsName, info)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddReplicaset provides a mock function with given fields: ctx, rsInfo, instances
func (_m *TopologyController) AddReplicaset(ctx context.Context, rsInfo vshard_router.ReplicasetInfo, instances []vshard_router.InstanceInfo) error {
	ret := _m.Called(ctx, rsInfo, instances)

	if len(ret) == 0 {
		panic("no return value specified for AddReplicaset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, vshard_router.ReplicasetInfo, []vshard_router.InstanceInfo) error); ok {
		r0 = rf(ctx, rsInfo, instances)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddReplicasets provides a mock function with given fields: ctx, replicasets
func (_m *TopologyController) AddReplicasets(ctx context.Context, replicasets map[vshard_router.ReplicasetInfo][]vshard_router.InstanceInfo) error {
	ret := _m.Called(ctx, replicasets)

	if len(ret) == 0 {
		panic("no return value specified for AddReplicasets")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, map[vshard_router.ReplicasetInfo][]vshard_router.InstanceInfo) error); ok {
		r0 = rf(ctx, replicasets)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveInstance provides a mock function with given fields: ctx, rsName, instanceName
func (_m *TopologyController) RemoveInstance(ctx context.Context, rsName string, instanceName string) error {
	ret := _m.Called(ctx, rsName, instanceName)

	if len(ret) == 0 {
		panic("no return value specified for RemoveInstance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, rsName, instanceName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveReplicaset provides a mock function with given fields: ctx, rsName
func (_m *TopologyController) RemoveReplicaset(ctx context.Context, rsName string) []error {
	ret := _m.Called(ctx, rsName)

	if len(ret) == 0 {
		panic("no return value specified for RemoveReplicaset")
	}

	var r0 []error
	if rf, ok := ret.Get(0).(func(context.Context, string) []error); ok {
		r0 = rf(ctx, rsName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]error)
		}
	}

	return r0
}

// NewTopologyController creates a new instance of TopologyController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTopologyController(t interface {
	mock.TestingT
	Cleanup(func())
}) *TopologyController {
	mock := &TopologyController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
