storage:
  topology:
    clusters:
      storage_1:
        replicaset_uuid: cbf06940-0790-498b-948d-042b62cf3d29
      storage_2:
        replicaset_uuid: ac522f65-aa94-4134-9f64-51ee384f1a54
    instances:
      storage_1_a:
        cluster: storage_1
        box:
          listen: 'tarantool-storage-1-a:3301'
          instance_uuid: '6E35AC64-1241-0001-0001-000000000000'
      storage_1_b:
        cluster: storage_1
        box:
          listen: 'tarantool-storage-1-b:3301'
          instance_uuid: '6E35AC64-1241-0001-0002-000000000000'
      storage_2_a:
        cluster: storage_2
        box:
          listen: 'tarantool-storage-2-a:3301'
          instance_uuid: '6E35AC64-1241-0002-0001-000000000000'
      storage_2_b:
        cluster: storage_2
        box:
          listen: 'tarantool-storage-2-b:3301'
          instance_uuid: '6E35AC64-1241-0002-0002-000000000000'