{
 "title": "GoLang Metrics",
 "description": "Golang Application Runtime metrics",
 "tags": [
  "go",
  "golang"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(go_goroutines, namespace)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(go_goroutines{namespace=\"$namespace\"}, pod)"
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(go_gc_duration_seconds,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Rate metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handling_seconds_count[2s])) by (grpc_method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handling_seconds_count[60s])) by (grpc_method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency P50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(grpc_server_handling_seconds_bucket{}[2s]))",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Latency P90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(grpc_server_handling_seconds_bucket{}[2s]))",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Latency P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(grpc_server_handling_seconds_bucket{}[2s]))",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Latency P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(grpc_server_handling_seconds_bucket{}[2s]))",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  { "title": "System metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Memory in Off-Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{namespace=\"$namespace\", pod=~\"$pod\", instance=~\"$instance\" }",
     "legendFormat": "mspan inuse"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{namespace=\"$namespace\", pod=~\"$pod\", instance=~\"$instance\"}",
     "legendFormat": "mspan sys"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{namespace=\"$namespace\", pod=~\"$pod\", instance=~\"$instance\"}",
     "legendFormat": "mcache inuse"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{namespace=\"$namespace\", pod=~\"$pod\", instance=~\"$instance\"}",
     "legendFormat": "mcache sys"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{namespace=\"$namespace\", pod=~\"$pod\", instance=~\"$instance\"}",
     "legendFormat": "buck hash sys"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{namespace=\"$namespace\", pod=~\"$pod\", instance=~\"$instance\"}",
     "legendFormat": "gc sys"
    },
    {
     "expr": "go_memstats_other_sys_bytes{namespace=\"$namespace\", pod=~\"$pod\", instance=~\"$instance\"} - go_memstats_other_sys_bytes{namespace=\"$namespace\", pod=~\"$pod\", instance=~\"$instance\"}",
     "legendFormat": "bytes of memory are used for other runtime allocations {pod={{pod}}}"
    },
    {
     "expr": "go_memstats_next_gc_bytes{namespace=\"$namespace\", pod=~\"$pod\", instance=~\"$instance\"}",
     "legendFormat": "next gc"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{namespace=\"$namespace\", pod=~\"$pod\", instance=~\"$instance\"}",
     "legendFormat": "heap alloc"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{namespace=\"$namespace\", pod=~\"$pod\", instance=~\"$instance\"}",
     "legendFormat": "heap sys"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{namespace=\"$namespace\", pod=~\"$pod\", instance=~\"$instance\"}",
     "legendFormat": "heap idle"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{namespace=\"$namespace\", pod=~\"$pod\", instance=~\"$instance\"}",
     "legendFormat": "heap inuse"
    },
    {
     "expr": "go_memstats_heap_released_bytes{namespace=\"$namespace\", pod=~\"$pod\", instance=~\"$instance\"}",
     "legendFormat": "heap released"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{namespace=\"$namespace\", pod=~\"$pod\", instance=~\"$instance\"}",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{namespace=\"$namespace\", pod=~\"$pod\", instance=~\"$instance\"}",
     "legendFormat": "stack sys"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{namespace=\"$namespace\", pod=~\"$pod\", instance=~\"$instance\"}",
     "legendFormat": "sys"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{namespace=\"$namespace\", pod=~\"$pod\", instance=~\"$instance\"} - go_memstats_frees_total{namespace=\"$namespace\", pod=~\"$pod\", instance=~\"$instance\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "timeseries",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{namespace=\"$namespace\", pod=~\"$pod\", instance=~\"$instance\", instance=~\"$instance\"}[1m])",
     "legendFormat": "mallocs rate"
    }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences",
   "type": "timeseries",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total{namespace=\"$namespace\", pod=~\"$pod\", instance=~\"$instance\"}[1m])",
     "legendFormat": "lookup rate"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{namespace=\"$namespace\", pod=~\"$pod\", instance=~\"$instance\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{namespace=\"$namespace\", pod=~\"$pod\", instance=~\"$instance\"}[1m])",
     "legendFormat": "alloc byte rate"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{namespace=\"$namespace\", pod=~\"$pod\", instance=~\"$instance\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  }
 ]
}