// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockpool

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	"github.com/tarantool/go-tarantool/v2"
	"github.com/tarantool/go-tarantool/v2/pool"
)

// NewPooler creates a new instance of Pooler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPooler(t interface {
	mock.TestingT
	Cleanup(func())
}) *Pooler {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &Pooler{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// Pooler is an autogenerated mock type for the Pooler type
type Pooler struct {
	mock.Mock
}

type Pooler_Expecter struct {
	mock *mock.Mock
}

func (_m *Pooler) EXPECT() *Pooler_Expecter {
	return &Pooler_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type Pooler
func (_mock *Pooler) Add(ctx context.Context, instance pool.Instance) error {
	ret := _mock.Called(ctx, instance)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pool.Instance) error); ok {
		r0 = returnFunc(ctx, instance)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Pooler_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type Pooler_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - instance pool.Instance
func (_e *Pooler_Expecter) Add(ctx any, instance any) *Pooler_Add_Call {
	return &Pooler_Add_Call{Call: _e.mock.On("Add", ctx, instance)}
}

func (_c *Pooler_Add_Call) Run(run func(ctx context.Context, instance pool.Instance)) *Pooler_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pool.Instance
		if args[1] != nil {
			arg1 = args[1].(pool.Instance)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Pooler_Add_Call) Return(err error) *Pooler_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Pooler_Add_Call) RunAndReturn(run func(ctx context.Context, instance pool.Instance) error) *Pooler_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Call provides a mock function for the type Pooler
func (_mock *Pooler) Call(functionName string, args interface{}, mode pool.Mode) ([]interface{}, error) {
	ret := _mock.Called(functionName, args, mode)

	if len(ret) == 0 {
		panic("no return value specified for Call")
	}

	var r0 []interface{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, interface{}, pool.Mode) ([]interface{}, error)); ok {
		return returnFunc(functionName, args, mode)
	}
	if returnFunc, ok := ret.Get(0).(func(string, interface{}, pool.Mode) []interface{}); ok {
		r0 = returnFunc(functionName, args, mode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, interface{}, pool.Mode) error); ok {
		r1 = returnFunc(functionName, args, mode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Pooler_Call_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Call'
type Pooler_Call_Call struct {
	*mock.Call
}

// Call is a helper method to define mock.On call
//   - functionName string
//   - args interface{}
//   - mode pool.Mode
func (_e *Pooler_Expecter) Call(functionName any, args any, mode any) *Pooler_Call_Call {
	return &Pooler_Call_Call{Call: _e.mock.On("Call", functionName, args, mode)}
}

func (_c *Pooler_Call_Call) Run(run func(functionName string, args interface{}, mode pool.Mode)) *Pooler_Call_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 pool.Mode
		if args[2] != nil {
			arg2 = args[2].(pool.Mode)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Pooler_Call_Call) Return(ifaceVals []interface{}, err error) *Pooler_Call_Call {
	_c.Call.Return(ifaceVals, err)
	return _c
}

func (_c *Pooler_Call_Call) RunAndReturn(run func(functionName string, args interface{}, mode pool.Mode) ([]interface{}, error)) *Pooler_Call_Call {
	_c.Call.Return(run)
	return _c
}

// Call16 provides a mock function for the type Pooler
func (_mock *Pooler) Call16(functionName string, args interface{}, mode pool.Mode) ([]interface{}, error) {
	ret := _mock.Called(functionName, args, mode)

	if len(ret) == 0 {
		panic("no return value specified for Call16")
	}

	var r0 []interface{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, interface{}, pool.Mode) ([]interface{}, error)); ok {
		return returnFunc(functionName, args, mode)
	}
	if returnFunc, ok := ret.Get(0).(func(string, interface{}, pool.Mode) []interface{}); ok {
		r0 = returnFunc(functionName, args, mode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, interface{}, pool.Mode) error); ok {
		r1 = returnFunc(functionName, args, mode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Pooler_Call16_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Call16'
type Pooler_Call16_Call struct {
	*mock.Call
}

// Call16 is a helper method to define mock.On call
//   - functionName string
//   - args interface{}
//   - mode pool.Mode
func (_e *Pooler_Expecter) Call16(functionName any, args any, mode any) *Pooler_Call16_Call {
	return &Pooler_Call16_Call{Call: _e.mock.On("Call16", functionName, args, mode)}
}

func (_c *Pooler_Call16_Call) Run(run func(functionName string, args interface{}, mode pool.Mode)) *Pooler_Call16_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 pool.Mode
		if args[2] != nil {
			arg2 = args[2].(pool.Mode)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Pooler_Call16_Call) Return(ifaceVals []interface{}, err error) *Pooler_Call16_Call {
	_c.Call.Return(ifaceVals, err)
	return _c
}

func (_c *Pooler_Call16_Call) RunAndReturn(run func(functionName string, args interface{}, mode pool.Mode) ([]interface{}, error)) *Pooler_Call16_Call {
	_c.Call.Return(run)
	return _c
}

// Call16Async provides a mock function for the type Pooler
func (_mock *Pooler) Call16Async(functionName string, args interface{}, mode pool.Mode) *tarantool.Future {
	ret := _mock.Called(functionName, args, mode)

	if len(ret) == 0 {
		panic("no return value specified for Call16Async")
	}

	var r0 *tarantool.Future
	if returnFunc, ok := ret.Get(0).(func(string, interface{}, pool.Mode) *tarantool.Future); ok {
		r0 = returnFunc(functionName, args, mode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tarantool.Future)
		}
	}
	return r0
}

// Pooler_Call16Async_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Call16Async'
type Pooler_Call16Async_Call struct {
	*mock.Call
}

// Call16Async is a helper method to define mock.On call
//   - functionName string
//   - args interface{}
//   - mode pool.Mode
func (_e *Pooler_Expecter) Call16Async(functionName any, args any, mode any) *Pooler_Call16Async_Call {
	return &Pooler_Call16Async_Call{Call: _e.mock.On("Call16Async", functionName, args, mode)}
}

func (_c *Pooler_Call16Async_Call) Run(run func(functionName string, args interface{}, mode pool.Mode)) *Pooler_Call16Async_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 pool.Mode
		if args[2] != nil {
			arg2 = args[2].(pool.Mode)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Pooler_Call16Async_Call) Return(future *tarantool.Future) *Pooler_Call16Async_Call {
	_c.Call.Return(future)
	return _c
}

func (_c *Pooler_Call16Async_Call) RunAndReturn(run func(functionName string, args interface{}, mode pool.Mode) *tarantool.Future) *Pooler_Call16Async_Call {
	_c.Call.Return(run)
	return _c
}

// Call16Typed provides a mock function for the type Pooler
func (_mock *Pooler) Call16Typed(functionName string, args interface{}, result interface{}, mode pool.Mode) error {
	ret := _mock.Called(functionName, args, result, mode)

	if len(ret) == 0 {
		panic("no return value specified for Call16Typed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, interface{}, interface{}, pool.Mode) error); ok {
		r0 = returnFunc(functionName, args, result, mode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Pooler_Call16Typed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Call16Typed'
type Pooler_Call16Typed_Call struct {
	*mock.Call
}

// Call16Typed is a helper method to define mock.On call
//   - functionName string
//   - args interface{}
//   - result interface{}
//   - mode pool.Mode
func (_e *Pooler_Expecter) Call16Typed(functionName any, args any, result any, mode any) *Pooler_Call16Typed_Call {
	return &Pooler_Call16Typed_Call{Call: _e.mock.On("Call16Typed", functionName, args, result, mode)}
}

func (_c *Pooler_Call16Typed_Call) Run(run func(functionName string, args interface{}, result interface{}, mode pool.Mode)) *Pooler_Call16Typed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 pool.Mode
		if args[3] != nil {
			arg3 = args[3].(pool.Mode)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Pooler_Call16Typed_Call) Return(err error) *Pooler_Call16Typed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Pooler_Call16Typed_Call) RunAndReturn(run func(functionName string, args interface{}, result interface{}, mode pool.Mode) error) *Pooler_Call16Typed_Call {
	_c.Call.Return(run)
	return _c
}

// Call17 provides a mock function for the type Pooler
func (_mock *Pooler) Call17(functionName string, args interface{}, mode pool.Mode) ([]interface{}, error) {
	ret := _mock.Called(functionName, args, mode)

	if len(ret) == 0 {
		panic("no return value specified for Call17")
	}

	var r0 []interface{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, interface{}, pool.Mode) ([]interface{}, error)); ok {
		return returnFunc(functionName, args, mode)
	}
	if returnFunc, ok := ret.Get(0).(func(string, interface{}, pool.Mode) []interface{}); ok {
		r0 = returnFunc(functionName, args, mode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, interface{}, pool.Mode) error); ok {
		r1 = returnFunc(functionName, args, mode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Pooler_Call17_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Call17'
type Pooler_Call17_Call struct {
	*mock.Call
}

// Call17 is a helper method to define mock.On call
//   - functionName string
//   - args interface{}
//   - mode pool.Mode
func (_e *Pooler_Expecter) Call17(functionName any, args any, mode any) *Pooler_Call17_Call {
	return &Pooler_Call17_Call{Call: _e.mock.On("Call17", functionName, args, mode)}
}

func (_c *Pooler_Call17_Call) Run(run func(functionName string, args interface{}, mode pool.Mode)) *Pooler_Call17_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 pool.Mode
		if args[2] != nil {
			arg2 = args[2].(pool.Mode)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Pooler_Call17_Call) Return(ifaceVals []interface{}, err error) *Pooler_Call17_Call {
	_c.Call.Return(ifaceVals, err)
	return _c
}

func (_c *Pooler_Call17_Call) RunAndReturn(run func(functionName string, args interface{}, mode pool.Mode) ([]interface{}, error)) *Pooler_Call17_Call {
	_c.Call.Return(run)
	return _c
}

// Call17Async provides a mock function for the type Pooler
func (_mock *Pooler) Call17Async(functionName string, args interface{}, mode pool.Mode) *tarantool.Future {
	ret := _mock.Called(functionName, args, mode)

	if len(ret) == 0 {
		panic("no return value specified for Call17Async")
	}

	var r0 *tarantool.Future
	if returnFunc, ok := ret.Get(0).(func(string, interface{}, pool.Mode) *tarantool.Future); ok {
		r0 = returnFunc(functionName, args, mode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tarantool.Future)
		}
	}
	return r0
}

// Pooler_Call17Async_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Call17Async'
type Pooler_Call17Async_Call struct {
	*mock.Call
}

// Call17Async is a helper method to define mock.On call
//   - functionName string
//   - args interface{}
//   - mode pool.Mode
func (_e *Pooler_Expecter) Call17Async(functionName any, args any, mode any) *Pooler_Call17Async_Call {
	return &Pooler_Call17Async_Call{Call: _e.mock.On("Call17Async", functionName, args, mode)}
}

func (_c *Pooler_Call17Async_Call) Run(run func(functionName string, args interface{}, mode pool.Mode)) *Pooler_Call17Async_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 pool.Mode
		if args[2] != nil {
			arg2 = args[2].(pool.Mode)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Pooler_Call17Async_Call) Return(future *tarantool.Future) *Pooler_Call17Async_Call {
	_c.Call.Return(future)
	return _c
}

func (_c *Pooler_Call17Async_Call) RunAndReturn(run func(functionName string, args interface{}, mode pool.Mode) *tarantool.Future) *Pooler_Call17Async_Call {
	_c.Call.Return(run)
	return _c
}

// Call17Typed provides a mock function for the type Pooler
func (_mock *Pooler) Call17Typed(functionName string, args interface{}, result interface{}, mode pool.Mode) error {
	ret := _mock.Called(functionName, args, result, mode)

	if len(ret) == 0 {
		panic("no return value specified for Call17Typed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, interface{}, interface{}, pool.Mode) error); ok {
		r0 = returnFunc(functionName, args, result, mode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Pooler_Call17Typed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Call17Typed'
type Pooler_Call17Typed_Call struct {
	*mock.Call
}

// Call17Typed is a helper method to define mock.On call
//   - functionName string
//   - args interface{}
//   - result interface{}
//   - mode pool.Mode
func (_e *Pooler_Expecter) Call17Typed(functionName any, args any, result any, mode any) *Pooler_Call17Typed_Call {
	return &Pooler_Call17Typed_Call{Call: _e.mock.On("Call17Typed", functionName, args, result, mode)}
}

func (_c *Pooler_Call17Typed_Call) Run(run func(functionName string, args interface{}, result interface{}, mode pool.Mode)) *Pooler_Call17Typed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 pool.Mode
		if args[3] != nil {
			arg3 = args[3].(pool.Mode)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Pooler_Call17Typed_Call) Return(err error) *Pooler_Call17Typed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Pooler_Call17Typed_Call) RunAndReturn(run func(functionName string, args interface{}, result interface{}, mode pool.Mode) error) *Pooler_Call17Typed_Call {
	_c.Call.Return(run)
	return _c
}

// CallAsync provides a mock function for the type Pooler
func (_mock *Pooler) CallAsync(functionName string, args interface{}, mode pool.Mode) *tarantool.Future {
	ret := _mock.Called(functionName, args, mode)

	if len(ret) == 0 {
		panic("no return value specified for CallAsync")
	}

	var r0 *tarantool.Future
	if returnFunc, ok := ret.Get(0).(func(string, interface{}, pool.Mode) *tarantool.Future); ok {
		r0 = returnFunc(functionName, args, mode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tarantool.Future)
		}
	}
	return r0
}

// Pooler_CallAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CallAsync'
type Pooler_CallAsync_Call struct {
	*mock.Call
}

// CallAsync is a helper method to define mock.On call
//   - functionName string
//   - args interface{}
//   - mode pool.Mode
func (_e *Pooler_Expecter) CallAsync(functionName any, args any, mode any) *Pooler_CallAsync_Call {
	return &Pooler_CallAsync_Call{Call: _e.mock.On("CallAsync", functionName, args, mode)}
}

func (_c *Pooler_CallAsync_Call) Run(run func(functionName string, args interface{}, mode pool.Mode)) *Pooler_CallAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 pool.Mode
		if args[2] != nil {
			arg2 = args[2].(pool.Mode)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Pooler_CallAsync_Call) Return(future *tarantool.Future) *Pooler_CallAsync_Call {
	_c.Call.Return(future)
	return _c
}

func (_c *Pooler_CallAsync_Call) RunAndReturn(run func(functionName string, args interface{}, mode pool.Mode) *tarantool.Future) *Pooler_CallAsync_Call {
	_c.Call.Return(run)
	return _c
}

// CallTyped provides a mock function for the type Pooler
func (_mock *Pooler) CallTyped(functionName string, args interface{}, result interface{}, mode pool.Mode) error {
	ret := _mock.Called(functionName, args, result, mode)

	if len(ret) == 0 {
		panic("no return value specified for CallTyped")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, interface{}, interface{}, pool.Mode) error); ok {
		r0 = returnFunc(functionName, args, result, mode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Pooler_CallTyped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CallTyped'
type Pooler_CallTyped_Call struct {
	*mock.Call
}

// CallTyped is a helper method to define mock.On call
//   - functionName string
//   - args interface{}
//   - result interface{}
//   - mode pool.Mode
func (_e *Pooler_Expecter) CallTyped(functionName any, args any, result any, mode any) *Pooler_CallTyped_Call {
	return &Pooler_CallTyped_Call{Call: _e.mock.On("CallTyped", functionName, args, result, mode)}
}

func (_c *Pooler_CallTyped_Call) Run(run func(functionName string, args interface{}, result interface{}, mode pool.Mode)) *Pooler_CallTyped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 pool.Mode
		if args[3] != nil {
			arg3 = args[3].(pool.Mode)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Pooler_CallTyped_Call) Return(err error) *Pooler_CallTyped_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Pooler_CallTyped_Call) RunAndReturn(run func(functionName string, args interface{}, result interface{}, mode pool.Mode) error) *Pooler_CallTyped_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type Pooler
func (_mock *Pooler) Close() []error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 []error
	if returnFunc, ok := ret.Get(0).(func() []error); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]error)
		}
	}
	return r0
}

// Pooler_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Pooler_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Pooler_Expecter) Close() *Pooler_Close_Call {
	return &Pooler_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Pooler_Close_Call) Run(run func()) *Pooler_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Pooler_Close_Call) Return(errs []error) *Pooler_Close_Call {
	_c.Call.Return(errs)
	return _c
}

func (_c *Pooler_Close_Call) RunAndReturn(run func() []error) *Pooler_Close_Call {
	_c.Call.Return(run)
	return _c
}

// CloseGraceful provides a mock function for the type Pooler
func (_mock *Pooler) CloseGraceful() []error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CloseGraceful")
	}

	var r0 []error
	if returnFunc, ok := ret.Get(0).(func() []error); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]error)
		}
	}
	return r0
}

// Pooler_CloseGraceful_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseGraceful'
type Pooler_CloseGraceful_Call struct {
	*mock.Call
}

// CloseGraceful is a helper method to define mock.On call
func (_e *Pooler_Expecter) CloseGraceful() *Pooler_CloseGraceful_Call {
	return &Pooler_CloseGraceful_Call{Call: _e.mock.On("CloseGraceful")}
}

func (_c *Pooler_CloseGraceful_Call) Run(run func()) *Pooler_CloseGraceful_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Pooler_CloseGraceful_Call) Return(errs []error) *Pooler_CloseGraceful_Call {
	_c.Call.Return(errs)
	return _c
}

func (_c *Pooler_CloseGraceful_Call) RunAndReturn(run func() []error) *Pooler_CloseGraceful_Call {
	_c.Call.Return(run)
	return _c
}

// ConfiguredTimeout provides a mock function for the type Pooler
func (_mock *Pooler) ConfiguredTimeout(mode pool.Mode) (time.Duration, error) {
	ret := _mock.Called(mode)

	if len(ret) == 0 {
		panic("no return value specified for ConfiguredTimeout")
	}

	var r0 time.Duration
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(pool.Mode) (time.Duration, error)); ok {
		return returnFunc(mode)
	}
	if returnFunc, ok := ret.Get(0).(func(pool.Mode) time.Duration); ok {
		r0 = returnFunc(mode)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	if returnFunc, ok := ret.Get(1).(func(pool.Mode) error); ok {
		r1 = returnFunc(mode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Pooler_ConfiguredTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfiguredTimeout'
type Pooler_ConfiguredTimeout_Call struct {
	*mock.Call
}

// ConfiguredTimeout is a helper method to define mock.On call
//   - mode pool.Mode
func (_e *Pooler_Expecter) ConfiguredTimeout(mode any) *Pooler_ConfiguredTimeout_Call {
	return &Pooler_ConfiguredTimeout_Call{Call: _e.mock.On("ConfiguredTimeout", mode)}
}

func (_c *Pooler_ConfiguredTimeout_Call) Run(run func(mode pool.Mode)) *Pooler_ConfiguredTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pool.Mode
		if args[0] != nil {
			arg0 = args[0].(pool.Mode)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Pooler_ConfiguredTimeout_Call) Return(duration time.Duration, err error) *Pooler_ConfiguredTimeout_Call {
	_c.Call.Return(duration, err)
	return _c
}

func (_c *Pooler_ConfiguredTimeout_Call) RunAndReturn(run func(mode pool.Mode) (time.Duration, error)) *Pooler_ConfiguredTimeout_Call {
	_c.Call.Return(run)
	return _c
}

// ConnectedNow provides a mock function for the type Pooler
func (_mock *Pooler) ConnectedNow(mode pool.Mode) (bool, error) {
	ret := _mock.Called(mode)

	if len(ret) == 0 {
		panic("no return value specified for ConnectedNow")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(pool.Mode) (bool, error)); ok {
		return returnFunc(mode)
	}
	if returnFunc, ok := ret.Get(0).(func(pool.Mode) bool); ok {
		r0 = returnFunc(mode)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(pool.Mode) error); ok {
		r1 = returnFunc(mode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Pooler_ConnectedNow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConnectedNow'
type Pooler_ConnectedNow_Call struct {
	*mock.Call
}

// ConnectedNow is a helper method to define mock.On call
//   - mode pool.Mode
func (_e *Pooler_Expecter) ConnectedNow(mode any) *Pooler_ConnectedNow_Call {
	return &Pooler_ConnectedNow_Call{Call: _e.mock.On("ConnectedNow", mode)}
}

func (_c *Pooler_ConnectedNow_Call) Run(run func(mode pool.Mode)) *Pooler_ConnectedNow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pool.Mode
		if args[0] != nil {
			arg0 = args[0].(pool.Mode)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Pooler_ConnectedNow_Call) Return(b bool, err error) *Pooler_ConnectedNow_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *Pooler_ConnectedNow_Call) RunAndReturn(run func(mode pool.Mode) (bool, error)) *Pooler_ConnectedNow_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type Pooler
func (_mock *Pooler) Delete(space interface{}, index interface{}, key interface{}, mode ...pool.Mode) ([]interface{}, error) {
	var tmpRet mock.Arguments
	if len(mode) > 0 {
		tmpRet = _mock.Called(space, index, key, mode)
	} else {
		tmpRet = _mock.Called(space, index, key)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 []interface{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(interface{}, interface{}, interface{}, ...pool.Mode) ([]interface{}, error)); ok {
		return returnFunc(space, index, key, mode...)
	}
	if returnFunc, ok := ret.Get(0).(func(interface{}, interface{}, interface{}, ...pool.Mode) []interface{}); ok {
		r0 = returnFunc(space, index, key, mode...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(interface{}, interface{}, interface{}, ...pool.Mode) error); ok {
		r1 = returnFunc(space, index, key, mode...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Pooler_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Pooler_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - space interface{}
//   - index interface{}
//   - key interface{}
//   - mode ...pool.Mode
func (_e *Pooler_Expecter) Delete(space any, index any, key any, mode ...any) *Pooler_Delete_Call {
	return &Pooler_Delete_Call{Call: _e.mock.On("Delete",
		append([]any{space, index, key}, mode...)...)}
}

func (_c *Pooler_Delete_Call) Run(run func(space interface{}, index interface{}, key interface{}, mode ...pool.Mode)) *Pooler_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 []pool.Mode
		var variadicArgs []pool.Mode
		if len(args) > 3 {
			variadicArgs = args[3].([]pool.Mode)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *Pooler_Delete_Call) Return(ifaceVals []interface{}, err error) *Pooler_Delete_Call {
	_c.Call.Return(ifaceVals, err)
	return _c
}

func (_c *Pooler_Delete_Call) RunAndReturn(run func(space interface{}, index interface{}, key interface{}, mode ...pool.Mode) ([]interface{}, error)) *Pooler_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAsync provides a mock function for the type Pooler
func (_mock *Pooler) DeleteAsync(space interface{}, index interface{}, key interface{}, mode ...pool.Mode) *tarantool.Future {
	var tmpRet mock.Arguments
	if len(mode) > 0 {
		tmpRet = _mock.Called(space, index, key, mode)
	} else {
		tmpRet = _mock.Called(space, index, key)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteAsync")
	}

	var r0 *tarantool.Future
	if returnFunc, ok := ret.Get(0).(func(interface{}, interface{}, interface{}, ...pool.Mode) *tarantool.Future); ok {
		r0 = returnFunc(space, index, key, mode...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tarantool.Future)
		}
	}
	return r0
}

// Pooler_DeleteAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAsync'
type Pooler_DeleteAsync_Call struct {
	*mock.Call
}

// DeleteAsync is a helper method to define mock.On call
//   - space interface{}
//   - index interface{}
//   - key interface{}
//   - mode ...pool.Mode
func (_e *Pooler_Expecter) DeleteAsync(space any, index any, key any, mode ...any) *Pooler_DeleteAsync_Call {
	return &Pooler_DeleteAsync_Call{Call: _e.mock.On("DeleteAsync",
		append([]any{space, index, key}, mode...)...)}
}

func (_c *Pooler_DeleteAsync_Call) Run(run func(space interface{}, index interface{}, key interface{}, mode ...pool.Mode)) *Pooler_DeleteAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 []pool.Mode
		var variadicArgs []pool.Mode
		if len(args) > 3 {
			variadicArgs = args[3].([]pool.Mode)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *Pooler_DeleteAsync_Call) Return(future *tarantool.Future) *Pooler_DeleteAsync_Call {
	_c.Call.Return(future)
	return _c
}

func (_c *Pooler_DeleteAsync_Call) RunAndReturn(run func(space interface{}, index interface{}, key interface{}, mode ...pool.Mode) *tarantool.Future) *Pooler_DeleteAsync_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTyped provides a mock function for the type Pooler
func (_mock *Pooler) DeleteTyped(space interface{}, index interface{}, key interface{}, result interface{}, mode ...pool.Mode) error {
	var tmpRet mock.Arguments
	if len(mode) > 0 {
		tmpRet = _mock.Called(space, index, key, result, mode)
	} else {
		tmpRet = _mock.Called(space, index, key, result)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteTyped")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(interface{}, interface{}, interface{}, interface{}, ...pool.Mode) error); ok {
		r0 = returnFunc(space, index, key, result, mode...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Pooler_DeleteTyped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTyped'
type Pooler_DeleteTyped_Call struct {
	*mock.Call
}

// DeleteTyped is a helper method to define mock.On call
//   - space interface{}
//   - index interface{}
//   - key interface{}
//   - result interface{}
//   - mode ...pool.Mode
func (_e *Pooler_Expecter) DeleteTyped(space any, index any, key any, result any, mode ...any) *Pooler_DeleteTyped_Call {
	return &Pooler_DeleteTyped_Call{Call: _e.mock.On("DeleteTyped",
		append([]any{space, index, key, result}, mode...)...)}
}

func (_c *Pooler_DeleteTyped_Call) Run(run func(space interface{}, index interface{}, key interface{}, result interface{}, mode ...pool.Mode)) *Pooler_DeleteTyped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 interface{}
		if args[3] != nil {
			arg3 = args[3].(interface{})
		}
		var arg4 []pool.Mode
		var variadicArgs []pool.Mode
		if len(args) > 4 {
			variadicArgs = args[4].([]pool.Mode)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *Pooler_DeleteTyped_Call) Return(err error) *Pooler_DeleteTyped_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Pooler_DeleteTyped_Call) RunAndReturn(run func(space interface{}, index interface{}, key interface{}, result interface{}, mode ...pool.Mode) error) *Pooler_DeleteTyped_Call {
	_c.Call.Return(run)
	return _c
}

// Do provides a mock function for the type Pooler
func (_mock *Pooler) Do(req tarantool.Request, mode pool.Mode) *tarantool.Future {
	ret := _mock.Called(req, mode)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 *tarantool.Future
	if returnFunc, ok := ret.Get(0).(func(tarantool.Request, pool.Mode) *tarantool.Future); ok {
		r0 = returnFunc(req, mode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tarantool.Future)
		}
	}
	return r0
}

// Pooler_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type Pooler_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - req tarantool.Request
//   - mode pool.Mode
func (_e *Pooler_Expecter) Do(req any, mode any) *Pooler_Do_Call {
	return &Pooler_Do_Call{Call: _e.mock.On("Do", req, mode)}
}

func (_c *Pooler_Do_Call) Run(run func(req tarantool.Request, mode pool.Mode)) *Pooler_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 tarantool.Request
		if args[0] != nil {
			arg0 = args[0].(tarantool.Request)
		}
		var arg1 pool.Mode
		if args[1] != nil {
			arg1 = args[1].(pool.Mode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Pooler_Do_Call) Return(fut *tarantool.Future) *Pooler_Do_Call {
	_c.Call.Return(fut)
	return _c
}

func (_c *Pooler_Do_Call) RunAndReturn(run func(req tarantool.Request, mode pool.Mode) *tarantool.Future) *Pooler_Do_Call {
	_c.Call.Return(run)
	return _c
}

// Eval provides a mock function for the type Pooler
func (_mock *Pooler) Eval(expr string, args interface{}, mode pool.Mode) ([]interface{}, error) {
	ret := _mock.Called(expr, args, mode)

	if len(ret) == 0 {
		panic("no return value specified for Eval")
	}

	var r0 []interface{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, interface{}, pool.Mode) ([]interface{}, error)); ok {
		return returnFunc(expr, args, mode)
	}
	if returnFunc, ok := ret.Get(0).(func(string, interface{}, pool.Mode) []interface{}); ok {
		r0 = returnFunc(expr, args, mode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, interface{}, pool.Mode) error); ok {
		r1 = returnFunc(expr, args, mode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Pooler_Eval_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Eval'
type Pooler_Eval_Call struct {
	*mock.Call
}

// Eval is a helper method to define mock.On call
//   - expr string
//   - args interface{}
//   - mode pool.Mode
func (_e *Pooler_Expecter) Eval(expr any, args any, mode any) *Pooler_Eval_Call {
	return &Pooler_Eval_Call{Call: _e.mock.On("Eval", expr, args, mode)}
}

func (_c *Pooler_Eval_Call) Run(run func(expr string, args interface{}, mode pool.Mode)) *Pooler_Eval_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 pool.Mode
		if args[2] != nil {
			arg2 = args[2].(pool.Mode)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Pooler_Eval_Call) Return(ifaceVals []interface{}, err error) *Pooler_Eval_Call {
	_c.Call.Return(ifaceVals, err)
	return _c
}

func (_c *Pooler_Eval_Call) RunAndReturn(run func(expr string, args interface{}, mode pool.Mode) ([]interface{}, error)) *Pooler_Eval_Call {
	_c.Call.Return(run)
	return _c
}

// EvalAsync provides a mock function for the type Pooler
func (_mock *Pooler) EvalAsync(expr string, args interface{}, mode pool.Mode) *tarantool.Future {
	ret := _mock.Called(expr, args, mode)

	if len(ret) == 0 {
		panic("no return value specified for EvalAsync")
	}

	var r0 *tarantool.Future
	if returnFunc, ok := ret.Get(0).(func(string, interface{}, pool.Mode) *tarantool.Future); ok {
		r0 = returnFunc(expr, args, mode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tarantool.Future)
		}
	}
	return r0
}

// Pooler_EvalAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvalAsync'
type Pooler_EvalAsync_Call struct {
	*mock.Call
}

// EvalAsync is a helper method to define mock.On call
//   - expr string
//   - args interface{}
//   - mode pool.Mode
func (_e *Pooler_Expecter) EvalAsync(expr any, args any, mode any) *Pooler_EvalAsync_Call {
	return &Pooler_EvalAsync_Call{Call: _e.mock.On("EvalAsync", expr, args, mode)}
}

func (_c *Pooler_EvalAsync_Call) Run(run func(expr string, args interface{}, mode pool.Mode)) *Pooler_EvalAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 pool.Mode
		if args[2] != nil {
			arg2 = args[2].(pool.Mode)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Pooler_EvalAsync_Call) Return(future *tarantool.Future) *Pooler_EvalAsync_Call {
	_c.Call.Return(future)
	return _c
}

func (_c *Pooler_EvalAsync_Call) RunAndReturn(run func(expr string, args interface{}, mode pool.Mode) *tarantool.Future) *Pooler_EvalAsync_Call {
	_c.Call.Return(run)
	return _c
}

// EvalTyped provides a mock function for the type Pooler
func (_mock *Pooler) EvalTyped(expr string, args interface{}, result interface{}, mode pool.Mode) error {
	ret := _mock.Called(expr, args, result, mode)

	if len(ret) == 0 {
		panic("no return value specified for EvalTyped")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, interface{}, interface{}, pool.Mode) error); ok {
		r0 = returnFunc(expr, args, result, mode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Pooler_EvalTyped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvalTyped'
type Pooler_EvalTyped_Call struct {
	*mock.Call
}

// EvalTyped is a helper method to define mock.On call
//   - expr string
//   - args interface{}
//   - result interface{}
//   - mode pool.Mode
func (_e *Pooler_Expecter) EvalTyped(expr any, args any, result any, mode any) *Pooler_EvalTyped_Call {
	return &Pooler_EvalTyped_Call{Call: _e.mock.On("EvalTyped", expr, args, result, mode)}
}

func (_c *Pooler_EvalTyped_Call) Run(run func(expr string, args interface{}, result interface{}, mode pool.Mode)) *Pooler_EvalTyped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 pool.Mode
		if args[3] != nil {
			arg3 = args[3].(pool.Mode)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Pooler_EvalTyped_Call) Return(err error) *Pooler_EvalTyped_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Pooler_EvalTyped_Call) RunAndReturn(run func(expr string, args interface{}, result interface{}, mode pool.Mode) error) *Pooler_EvalTyped_Call {
	_c.Call.Return(run)
	return _c
}

// Execute provides a mock function for the type Pooler
func (_mock *Pooler) Execute(expr string, args interface{}, mode pool.Mode) ([]interface{}, error) {
	ret := _mock.Called(expr, args, mode)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []interface{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, interface{}, pool.Mode) ([]interface{}, error)); ok {
		return returnFunc(expr, args, mode)
	}
	if returnFunc, ok := ret.Get(0).(func(string, interface{}, pool.Mode) []interface{}); ok {
		r0 = returnFunc(expr, args, mode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, interface{}, pool.Mode) error); ok {
		r1 = returnFunc(expr, args, mode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Pooler_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type Pooler_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - expr string
//   - args interface{}
//   - mode pool.Mode
func (_e *Pooler_Expecter) Execute(expr any, args any, mode any) *Pooler_Execute_Call {
	return &Pooler_Execute_Call{Call: _e.mock.On("Execute", expr, args, mode)}
}

func (_c *Pooler_Execute_Call) Run(run func(expr string, args interface{}, mode pool.Mode)) *Pooler_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 pool.Mode
		if args[2] != nil {
			arg2 = args[2].(pool.Mode)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Pooler_Execute_Call) Return(ifaceVals []interface{}, err error) *Pooler_Execute_Call {
	_c.Call.Return(ifaceVals, err)
	return _c
}

func (_c *Pooler_Execute_Call) RunAndReturn(run func(expr string, args interface{}, mode pool.Mode) ([]interface{}, error)) *Pooler_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteAsync provides a mock function for the type Pooler
func (_mock *Pooler) ExecuteAsync(expr string, args interface{}, mode pool.Mode) *tarantool.Future {
	ret := _mock.Called(expr, args, mode)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteAsync")
	}

	var r0 *tarantool.Future
	if returnFunc, ok := ret.Get(0).(func(string, interface{}, pool.Mode) *tarantool.Future); ok {
		r0 = returnFunc(expr, args, mode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tarantool.Future)
		}
	}
	return r0
}

// Pooler_ExecuteAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteAsync'
type Pooler_ExecuteAsync_Call struct {
	*mock.Call
}

// ExecuteAsync is a helper method to define mock.On call
//   - expr string
//   - args interface{}
//   - mode pool.Mode
func (_e *Pooler_Expecter) ExecuteAsync(expr any, args any, mode any) *Pooler_ExecuteAsync_Call {
	return &Pooler_ExecuteAsync_Call{Call: _e.mock.On("ExecuteAsync", expr, args, mode)}
}

func (_c *Pooler_ExecuteAsync_Call) Run(run func(expr string, args interface{}, mode pool.Mode)) *Pooler_ExecuteAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 pool.Mode
		if args[2] != nil {
			arg2 = args[2].(pool.Mode)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Pooler_ExecuteAsync_Call) Return(future *tarantool.Future) *Pooler_ExecuteAsync_Call {
	_c.Call.Return(future)
	return _c
}

func (_c *Pooler_ExecuteAsync_Call) RunAndReturn(run func(expr string, args interface{}, mode pool.Mode) *tarantool.Future) *Pooler_ExecuteAsync_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteTyped provides a mock function for the type Pooler
func (_mock *Pooler) ExecuteTyped(expr string, args interface{}, result interface{}, mode pool.Mode) (tarantool.SQLInfo, []tarantool.ColumnMetaData, error) {
	ret := _mock.Called(expr, args, result, mode)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteTyped")
	}

	var r0 tarantool.SQLInfo
	var r1 []tarantool.ColumnMetaData
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, interface{}, interface{}, pool.Mode) (tarantool.SQLInfo, []tarantool.ColumnMetaData, error)); ok {
		return returnFunc(expr, args, result, mode)
	}
	if returnFunc, ok := ret.Get(0).(func(string, interface{}, interface{}, pool.Mode) tarantool.SQLInfo); ok {
		r0 = returnFunc(expr, args, result, mode)
	} else {
		r0 = ret.Get(0).(tarantool.SQLInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(string, interface{}, interface{}, pool.Mode) []tarantool.ColumnMetaData); ok {
		r1 = returnFunc(expr, args, result, mode)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]tarantool.ColumnMetaData)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(string, interface{}, interface{}, pool.Mode) error); ok {
		r2 = returnFunc(expr, args, result, mode)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Pooler_ExecuteTyped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteTyped'
type Pooler_ExecuteTyped_Call struct {
	*mock.Call
}

// ExecuteTyped is a helper method to define mock.On call
//   - expr string
//   - args interface{}
//   - result interface{}
//   - mode pool.Mode
func (_e *Pooler_Expecter) ExecuteTyped(expr any, args any, result any, mode any) *Pooler_ExecuteTyped_Call {
	return &Pooler_ExecuteTyped_Call{Call: _e.mock.On("ExecuteTyped", expr, args, result, mode)}
}

func (_c *Pooler_ExecuteTyped_Call) Run(run func(expr string, args interface{}, result interface{}, mode pool.Mode)) *Pooler_ExecuteTyped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 pool.Mode
		if args[3] != nil {
			arg3 = args[3].(pool.Mode)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Pooler_ExecuteTyped_Call) Return(sQLInfo tarantool.SQLInfo, columnMetaDatas []tarantool.ColumnMetaData, err error) *Pooler_ExecuteTyped_Call {
	_c.Call.Return(sQLInfo, columnMetaDatas, err)
	return _c
}

func (_c *Pooler_ExecuteTyped_Call) RunAndReturn(run func(expr string, args interface{}, result interface{}, mode pool.Mode) (tarantool.SQLInfo, []tarantool.ColumnMetaData, error)) *Pooler_ExecuteTyped_Call {
	_c.Call.Return(run)
	return _c
}

// GetInfo provides a mock function for the type Pooler
func (_mock *Pooler) GetInfo() map[string]pool.ConnectionInfo {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetInfo")
	}

	var r0 map[string]pool.ConnectionInfo
	if returnFunc, ok := ret.Get(0).(func() map[string]pool.ConnectionInfo); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]pool.ConnectionInfo)
		}
	}
	return r0
}

// Pooler_GetInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInfo'
type Pooler_GetInfo_Call struct {
	*mock.Call
}

// GetInfo is a helper method to define mock.On call
func (_e *Pooler_Expecter) GetInfo() *Pooler_GetInfo_Call {
	return &Pooler_GetInfo_Call{Call: _e.mock.On("GetInfo")}
}

func (_c *Pooler_GetInfo_Call) Run(run func()) *Pooler_GetInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Pooler_GetInfo_Call) Return(stringToConnectionInfo map[string]pool.ConnectionInfo) *Pooler_GetInfo_Call {
	_c.Call.Return(stringToConnectionInfo)
	return _c
}

func (_c *Pooler_GetInfo_Call) RunAndReturn(run func() map[string]pool.ConnectionInfo) *Pooler_GetInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetTyped provides a mock function for the type Pooler
func (_mock *Pooler) GetTyped(space interface{}, index interface{}, key interface{}, result interface{}, mode ...pool.Mode) error {
	var tmpRet mock.Arguments
	if len(mode) > 0 {
		tmpRet = _mock.Called(space, index, key, result, mode)
	} else {
		tmpRet = _mock.Called(space, index, key, result)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetTyped")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(interface{}, interface{}, interface{}, interface{}, ...pool.Mode) error); ok {
		r0 = returnFunc(space, index, key, result, mode...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Pooler_GetTyped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTyped'
type Pooler_GetTyped_Call struct {
	*mock.Call
}

// GetTyped is a helper method to define mock.On call
//   - space interface{}
//   - index interface{}
//   - key interface{}
//   - result interface{}
//   - mode ...pool.Mode
func (_e *Pooler_Expecter) GetTyped(space any, index any, key any, result any, mode ...any) *Pooler_GetTyped_Call {
	return &Pooler_GetTyped_Call{Call: _e.mock.On("GetTyped",
		append([]any{space, index, key, result}, mode...)...)}
}

func (_c *Pooler_GetTyped_Call) Run(run func(space interface{}, index interface{}, key interface{}, result interface{}, mode ...pool.Mode)) *Pooler_GetTyped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 interface{}
		if args[3] != nil {
			arg3 = args[3].(interface{})
		}
		var arg4 []pool.Mode
		var variadicArgs []pool.Mode
		if len(args) > 4 {
			variadicArgs = args[4].([]pool.Mode)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *Pooler_GetTyped_Call) Return(err error) *Pooler_GetTyped_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Pooler_GetTyped_Call) RunAndReturn(run func(space interface{}, index interface{}, key interface{}, result interface{}, mode ...pool.Mode) error) *Pooler_GetTyped_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type Pooler
func (_mock *Pooler) Insert(space interface{}, tuple interface{}, mode ...pool.Mode) ([]interface{}, error) {
	var tmpRet mock.Arguments
	if len(mode) > 0 {
		tmpRet = _mock.Called(space, tuple, mode)
	} else {
		tmpRet = _mock.Called(space, tuple)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 []interface{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(interface{}, interface{}, ...pool.Mode) ([]interface{}, error)); ok {
		return returnFunc(space, tuple, mode...)
	}
	if returnFunc, ok := ret.Get(0).(func(interface{}, interface{}, ...pool.Mode) []interface{}); ok {
		r0 = returnFunc(space, tuple, mode...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(interface{}, interface{}, ...pool.Mode) error); ok {
		r1 = returnFunc(space, tuple, mode...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Pooler_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type Pooler_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - space interface{}
//   - tuple interface{}
//   - mode ...pool.Mode
func (_e *Pooler_Expecter) Insert(space any, tuple any, mode ...any) *Pooler_Insert_Call {
	return &Pooler_Insert_Call{Call: _e.mock.On("Insert",
		append([]any{space, tuple}, mode...)...)}
}

func (_c *Pooler_Insert_Call) Run(run func(space interface{}, tuple interface{}, mode ...pool.Mode)) *Pooler_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []pool.Mode
		var variadicArgs []pool.Mode
		if len(args) > 2 {
			variadicArgs = args[2].([]pool.Mode)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Pooler_Insert_Call) Return(ifaceVals []interface{}, err error) *Pooler_Insert_Call {
	_c.Call.Return(ifaceVals, err)
	return _c
}

func (_c *Pooler_Insert_Call) RunAndReturn(run func(space interface{}, tuple interface{}, mode ...pool.Mode) ([]interface{}, error)) *Pooler_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// InsertAsync provides a mock function for the type Pooler
func (_mock *Pooler) InsertAsync(space interface{}, tuple interface{}, mode ...pool.Mode) *tarantool.Future {
	var tmpRet mock.Arguments
	if len(mode) > 0 {
		tmpRet = _mock.Called(space, tuple, mode)
	} else {
		tmpRet = _mock.Called(space, tuple)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for InsertAsync")
	}

	var r0 *tarantool.Future
	if returnFunc, ok := ret.Get(0).(func(interface{}, interface{}, ...pool.Mode) *tarantool.Future); ok {
		r0 = returnFunc(space, tuple, mode...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tarantool.Future)
		}
	}
	return r0
}

// Pooler_InsertAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertAsync'
type Pooler_InsertAsync_Call struct {
	*mock.Call
}

// InsertAsync is a helper method to define mock.On call
//   - space interface{}
//   - tuple interface{}
//   - mode ...pool.Mode
func (_e *Pooler_Expecter) InsertAsync(space any, tuple any, mode ...any) *Pooler_InsertAsync_Call {
	return &Pooler_InsertAsync_Call{Call: _e.mock.On("InsertAsync",
		append([]any{space, tuple}, mode...)...)}
}

func (_c *Pooler_InsertAsync_Call) Run(run func(space interface{}, tuple interface{}, mode ...pool.Mode)) *Pooler_InsertAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []pool.Mode
		var variadicArgs []pool.Mode
		if len(args) > 2 {
			variadicArgs = args[2].([]pool.Mode)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Pooler_InsertAsync_Call) Return(future *tarantool.Future) *Pooler_InsertAsync_Call {
	_c.Call.Return(future)
	return _c
}

func (_c *Pooler_InsertAsync_Call) RunAndReturn(run func(space interface{}, tuple interface{}, mode ...pool.Mode) *tarantool.Future) *Pooler_InsertAsync_Call {
	_c.Call.Return(run)
	return _c
}

// InsertTyped provides a mock function for the type Pooler
func (_mock *Pooler) InsertTyped(space interface{}, tuple interface{}, result interface{}, mode ...pool.Mode) error {
	var tmpRet mock.Arguments
	if len(mode) > 0 {
		tmpRet = _mock.Called(space, tuple, result, mode)
	} else {
		tmpRet = _mock.Called(space, tuple, result)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for InsertTyped")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(interface{}, interface{}, interface{}, ...pool.Mode) error); ok {
		r0 = returnFunc(space, tuple, result, mode...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Pooler_InsertTyped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertTyped'
type Pooler_InsertTyped_Call struct {
	*mock.Call
}

// InsertTyped is a helper method to define mock.On call
//   - space interface{}
//   - tuple interface{}
//   - result interface{}
//   - mode ...pool.Mode
func (_e *Pooler_Expecter) InsertTyped(space any, tuple any, result any, mode ...any) *Pooler_InsertTyped_Call {
	return &Pooler_InsertTyped_Call{Call: _e.mock.On("InsertTyped",
		append([]any{space, tuple, result}, mode...)...)}
}

func (_c *Pooler_InsertTyped_Call) Run(run func(space interface{}, tuple interface{}, result interface{}, mode ...pool.Mode)) *Pooler_InsertTyped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 []pool.Mode
		var variadicArgs []pool.Mode
		if len(args) > 3 {
			variadicArgs = args[3].([]pool.Mode)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *Pooler_InsertTyped_Call) Return(err error) *Pooler_InsertTyped_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Pooler_InsertTyped_Call) RunAndReturn(run func(space interface{}, tuple interface{}, result interface{}, mode ...pool.Mode) error) *Pooler_InsertTyped_Call {
	_c.Call.Return(run)
	return _c
}

// NewPrepared provides a mock function for the type Pooler
func (_mock *Pooler) NewPrepared(expr string, mode pool.Mode) (*tarantool.Prepared, error) {
	ret := _mock.Called(expr, mode)

	if len(ret) == 0 {
		panic("no return value specified for NewPrepared")
	}

	var r0 *tarantool.Prepared
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, pool.Mode) (*tarantool.Prepared, error)); ok {
		return returnFunc(expr, mode)
	}
	if returnFunc, ok := ret.Get(0).(func(string, pool.Mode) *tarantool.Prepared); ok {
		r0 = returnFunc(expr, mode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tarantool.Prepared)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, pool.Mode) error); ok {
		r1 = returnFunc(expr, mode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Pooler_NewPrepared_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewPrepared'
type Pooler_NewPrepared_Call struct {
	*mock.Call
}

// NewPrepared is a helper method to define mock.On call
//   - expr string
//   - mode pool.Mode
func (_e *Pooler_Expecter) NewPrepared(expr any, mode any) *Pooler_NewPrepared_Call {
	return &Pooler_NewPrepared_Call{Call: _e.mock.On("NewPrepared", expr, mode)}
}

func (_c *Pooler_NewPrepared_Call) Run(run func(expr string, mode pool.Mode)) *Pooler_NewPrepared_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 pool.Mode
		if args[1] != nil {
			arg1 = args[1].(pool.Mode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Pooler_NewPrepared_Call) Return(prepared *tarantool.Prepared, err error) *Pooler_NewPrepared_Call {
	_c.Call.Return(prepared, err)
	return _c
}

func (_c *Pooler_NewPrepared_Call) RunAndReturn(run func(expr string, mode pool.Mode) (*tarantool.Prepared, error)) *Pooler_NewPrepared_Call {
	_c.Call.Return(run)
	return _c
}

// NewStream provides a mock function for the type Pooler
func (_mock *Pooler) NewStream(mode pool.Mode) (*tarantool.Stream, error) {
	ret := _mock.Called(mode)

	if len(ret) == 0 {
		panic("no return value specified for NewStream")
	}

	var r0 *tarantool.Stream
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(pool.Mode) (*tarantool.Stream, error)); ok {
		return returnFunc(mode)
	}
	if returnFunc, ok := ret.Get(0).(func(pool.Mode) *tarantool.Stream); ok {
		r0 = returnFunc(mode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tarantool.Stream)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(pool.Mode) error); ok {
		r1 = returnFunc(mode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Pooler_NewStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewStream'
type Pooler_NewStream_Call struct {
	*mock.Call
}

// NewStream is a helper method to define mock.On call
//   - mode pool.Mode
func (_e *Pooler_Expecter) NewStream(mode any) *Pooler_NewStream_Call {
	return &Pooler_NewStream_Call{Call: _e.mock.On("NewStream", mode)}
}

func (_c *Pooler_NewStream_Call) Run(run func(mode pool.Mode)) *Pooler_NewStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pool.Mode
		if args[0] != nil {
			arg0 = args[0].(pool.Mode)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Pooler_NewStream_Call) Return(stream *tarantool.Stream, err error) *Pooler_NewStream_Call {
	_c.Call.Return(stream, err)
	return _c
}

func (_c *Pooler_NewStream_Call) RunAndReturn(run func(mode pool.Mode) (*tarantool.Stream, error)) *Pooler_NewStream_Call {
	_c.Call.Return(run)
	return _c
}

// NewWatcher provides a mock function for the type Pooler
func (_mock *Pooler) NewWatcher(key string, callback tarantool.WatchCallback, mode pool.Mode) (tarantool.Watcher, error) {
	ret := _mock.Called(key, callback, mode)

	if len(ret) == 0 {
		panic("no return value specified for NewWatcher")
	}

	var r0 tarantool.Watcher
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, tarantool.WatchCallback, pool.Mode) (tarantool.Watcher, error)); ok {
		return returnFunc(key, callback, mode)
	}
	if returnFunc, ok := ret.Get(0).(func(string, tarantool.WatchCallback, pool.Mode) tarantool.Watcher); ok {
		r0 = returnFunc(key, callback, mode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tarantool.Watcher)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, tarantool.WatchCallback, pool.Mode) error); ok {
		r1 = returnFunc(key, callback, mode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Pooler_NewWatcher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewWatcher'
type Pooler_NewWatcher_Call struct {
	*mock.Call
}

// NewWatcher is a helper method to define mock.On call
//   - key string
//   - callback tarantool.WatchCallback
//   - mode pool.Mode
func (_e *Pooler_Expecter) NewWatcher(key any, callback any, mode any) *Pooler_NewWatcher_Call {
	return &Pooler_NewWatcher_Call{Call: _e.mock.On("NewWatcher", key, callback, mode)}
}

func (_c *Pooler_NewWatcher_Call) Run(run func(key string, callback tarantool.WatchCallback, mode pool.Mode)) *Pooler_NewWatcher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 tarantool.WatchCallback
		if args[1] != nil {
			arg1 = args[1].(tarantool.WatchCallback)
		}
		var arg2 pool.Mode
		if args[2] != nil {
			arg2 = args[2].(pool.Mode)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Pooler_NewWatcher_Call) Return(watcher tarantool.Watcher, err error) *Pooler_NewWatcher_Call {
	_c.Call.Return(watcher, err)
	return _c
}

func (_c *Pooler_NewWatcher_Call) RunAndReturn(run func(key string, callback tarantool.WatchCallback, mode pool.Mode) (tarantool.Watcher, error)) *Pooler_NewWatcher_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type Pooler
func (_mock *Pooler) Ping(mode pool.Mode) ([]interface{}, error) {
	ret := _mock.Called(mode)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 []interface{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(pool.Mode) ([]interface{}, error)); ok {
		return returnFunc(mode)
	}
	if returnFunc, ok := ret.Get(0).(func(pool.Mode) []interface{}); ok {
		r0 = returnFunc(mode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(pool.Mode) error); ok {
		r1 = returnFunc(mode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Pooler_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type Pooler_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - mode pool.Mode
func (_e *Pooler_Expecter) Ping(mode any) *Pooler_Ping_Call {
	return &Pooler_Ping_Call{Call: _e.mock.On("Ping", mode)}
}

func (_c *Pooler_Ping_Call) Run(run func(mode pool.Mode)) *Pooler_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pool.Mode
		if args[0] != nil {
			arg0 = args[0].(pool.Mode)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Pooler_Ping_Call) Return(ifaceVals []interface{}, err error) *Pooler_Ping_Call {
	_c.Call.Return(ifaceVals, err)
	return _c
}

func (_c *Pooler_Ping_Call) RunAndReturn(run func(mode pool.Mode) ([]interface{}, error)) *Pooler_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type Pooler
func (_mock *Pooler) Remove(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Pooler_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type Pooler_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - name string
func (_e *Pooler_Expecter) Remove(name any) *Pooler_Remove_Call {
	return &Pooler_Remove_Call{Call: _e.mock.On("Remove", name)}
}

func (_c *Pooler_Remove_Call) Run(run func(name string)) *Pooler_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Pooler_Remove_Call) Return(err error) *Pooler_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Pooler_Remove_Call) RunAndReturn(run func(name string) error) *Pooler_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Replace provides a mock function for the type Pooler
func (_mock *Pooler) Replace(space interface{}, tuple interface{}, mode ...pool.Mode) ([]interface{}, error) {
	var tmpRet mock.Arguments
	if len(mode) > 0 {
		tmpRet = _mock.Called(space, tuple, mode)
	} else {
		tmpRet = _mock.Called(space, tuple)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Replace")
	}

	var r0 []interface{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(interface{}, interface{}, ...pool.Mode) ([]interface{}, error)); ok {
		return returnFunc(space, tuple, mode...)
	}
	if returnFunc, ok := ret.Get(0).(func(interface{}, interface{}, ...pool.Mode) []interface{}); ok {
		r0 = returnFunc(space, tuple, mode...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(interface{}, interface{}, ...pool.Mode) error); ok {
		r1 = returnFunc(space, tuple, mode...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Pooler_Replace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Replace'
type Pooler_Replace_Call struct {
	*mock.Call
}

// Replace is a helper method to define mock.On call
//   - space interface{}
//   - tuple interface{}
//   - mode ...pool.Mode
func (_e *Pooler_Expecter) Replace(space any, tuple any, mode ...any) *Pooler_Replace_Call {
	return &Pooler_Replace_Call{Call: _e.mock.On("Replace",
		append([]any{space, tuple}, mode...)...)}
}

func (_c *Pooler_Replace_Call) Run(run func(space interface{}, tuple interface{}, mode ...pool.Mode)) *Pooler_Replace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []pool.Mode
		var variadicArgs []pool.Mode
		if len(args) > 2 {
			variadicArgs = args[2].([]pool.Mode)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Pooler_Replace_Call) Return(ifaceVals []interface{}, err error) *Pooler_Replace_Call {
	_c.Call.Return(ifaceVals, err)
	return _c
}

func (_c *Pooler_Replace_Call) RunAndReturn(run func(space interface{}, tuple interface{}, mode ...pool.Mode) ([]interface{}, error)) *Pooler_Replace_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceAsync provides a mock function for the type Pooler
func (_mock *Pooler) ReplaceAsync(space interface{}, tuple interface{}, mode ...pool.Mode) *tarantool.Future {
	var tmpRet mock.Arguments
	if len(mode) > 0 {
		tmpRet = _mock.Called(space, tuple, mode)
	} else {
		tmpRet = _mock.Called(space, tuple)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ReplaceAsync")
	}

	var r0 *tarantool.Future
	if returnFunc, ok := ret.Get(0).(func(interface{}, interface{}, ...pool.Mode) *tarantool.Future); ok {
		r0 = returnFunc(space, tuple, mode...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tarantool.Future)
		}
	}
	return r0
}

// Pooler_ReplaceAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceAsync'
type Pooler_ReplaceAsync_Call struct {
	*mock.Call
}

// ReplaceAsync is a helper method to define mock.On call
//   - space interface{}
//   - tuple interface{}
//   - mode ...pool.Mode
func (_e *Pooler_Expecter) ReplaceAsync(space any, tuple any, mode ...any) *Pooler_ReplaceAsync_Call {
	return &Pooler_ReplaceAsync_Call{Call: _e.mock.On("ReplaceAsync",
		append([]any{space, tuple}, mode...)...)}
}

func (_c *Pooler_ReplaceAsync_Call) Run(run func(space interface{}, tuple interface{}, mode ...pool.Mode)) *Pooler_ReplaceAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []pool.Mode
		var variadicArgs []pool.Mode
		if len(args) > 2 {
			variadicArgs = args[2].([]pool.Mode)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Pooler_ReplaceAsync_Call) Return(future *tarantool.Future) *Pooler_ReplaceAsync_Call {
	_c.Call.Return(future)
	return _c
}

func (_c *Pooler_ReplaceAsync_Call) RunAndReturn(run func(space interface{}, tuple interface{}, mode ...pool.Mode) *tarantool.Future) *Pooler_ReplaceAsync_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceTyped provides a mock function for the type Pooler
func (_mock *Pooler) ReplaceTyped(space interface{}, tuple interface{}, result interface{}, mode ...pool.Mode) error {
	var tmpRet mock.Arguments
	if len(mode) > 0 {
		tmpRet = _mock.Called(space, tuple, result, mode)
	} else {
		tmpRet = _mock.Called(space, tuple, result)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ReplaceTyped")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(interface{}, interface{}, interface{}, ...pool.Mode) error); ok {
		r0 = returnFunc(space, tuple, result, mode...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Pooler_ReplaceTyped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceTyped'
type Pooler_ReplaceTyped_Call struct {
	*mock.Call
}

// ReplaceTyped is a helper method to define mock.On call
//   - space interface{}
//   - tuple interface{}
//   - result interface{}
//   - mode ...pool.Mode
func (_e *Pooler_Expecter) ReplaceTyped(space any, tuple any, result any, mode ...any) *Pooler_ReplaceTyped_Call {
	return &Pooler_ReplaceTyped_Call{Call: _e.mock.On("ReplaceTyped",
		append([]any{space, tuple, result}, mode...)...)}
}

func (_c *Pooler_ReplaceTyped_Call) Run(run func(space interface{}, tuple interface{}, result interface{}, mode ...pool.Mode)) *Pooler_ReplaceTyped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 []pool.Mode
		var variadicArgs []pool.Mode
		if len(args) > 3 {
			variadicArgs = args[3].([]pool.Mode)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *Pooler_ReplaceTyped_Call) Return(err error) *Pooler_ReplaceTyped_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Pooler_ReplaceTyped_Call) RunAndReturn(run func(space interface{}, tuple interface{}, result interface{}, mode ...pool.Mode) error) *Pooler_ReplaceTyped_Call {
	_c.Call.Return(run)
	return _c
}

// Select provides a mock function for the type Pooler
func (_mock *Pooler) Select(space interface{}, index interface{}, offset uint32, limit uint32, iterator tarantool.Iter, key interface{}, mode ...pool.Mode) ([]interface{}, error) {
	var tmpRet mock.Arguments
	if len(mode) > 0 {
		tmpRet = _mock.Called(space, index, offset, limit, iterator, key, mode)
	} else {
		tmpRet = _mock.Called(space, index, offset, limit, iterator, key)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Select")
	}

	var r0 []interface{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(interface{}, interface{}, uint32, uint32, tarantool.Iter, interface{}, ...pool.Mode) ([]interface{}, error)); ok {
		return returnFunc(space, index, offset, limit, iterator, key, mode...)
	}
	if returnFunc, ok := ret.Get(0).(func(interface{}, interface{}, uint32, uint32, tarantool.Iter, interface{}, ...pool.Mode) []interface{}); ok {
		r0 = returnFunc(space, index, offset, limit, iterator, key, mode...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(interface{}, interface{}, uint32, uint32, tarantool.Iter, interface{}, ...pool.Mode) error); ok {
		r1 = returnFunc(space, index, offset, limit, iterator, key, mode...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Pooler_Select_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Select'
type Pooler_Select_Call struct {
	*mock.Call
}

// Select is a helper method to define mock.On call
//   - space interface{}
//   - index interface{}
//   - offset uint32
//   - limit uint32
//   - iterator tarantool.Iter
//   - key interface{}
//   - mode ...pool.Mode
func (_e *Pooler_Expecter) Select(space any, index any, offset any, limit any, iterator any, key any, mode ...any) *Pooler_Select_Call {
	return &Pooler_Select_Call{Call: _e.mock.On("Select",
		append([]any{space, index, offset, limit, iterator, key}, mode...)...)}
}

func (_c *Pooler_Select_Call) Run(run func(space interface{}, index interface{}, offset uint32, limit uint32, iterator tarantool.Iter, key interface{}, mode ...pool.Mode)) *Pooler_Select_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 uint32
		if args[2] != nil {
			arg2 = args[2].(uint32)
		}
		var arg3 uint32
		if args[3] != nil {
			arg3 = args[3].(uint32)
		}
		var arg4 tarantool.Iter
		if args[4] != nil {
			arg4 = args[4].(tarantool.Iter)
		}
		var arg5 interface{}
		if args[5] != nil {
			arg5 = args[5].(interface{})
		}
		var arg6 []pool.Mode
		var variadicArgs []pool.Mode
		if len(args) > 6 {
			variadicArgs = args[6].([]pool.Mode)
		}
		arg6 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6...,
		)
	})
	return _c
}

func (_c *Pooler_Select_Call) Return(ifaceVals []interface{}, err error) *Pooler_Select_Call {
	_c.Call.Return(ifaceVals, err)
	return _c
}

func (_c *Pooler_Select_Call) RunAndReturn(run func(space interface{}, index interface{}, offset uint32, limit uint32, iterator tarantool.Iter, key interface{}, mode ...pool.Mode) ([]interface{}, error)) *Pooler_Select_Call {
	_c.Call.Return(run)
	return _c
}

// SelectAsync provides a mock function for the type Pooler
func (_mock *Pooler) SelectAsync(space interface{}, index interface{}, offset uint32, limit uint32, iterator tarantool.Iter, key interface{}, mode ...pool.Mode) *tarantool.Future {
	var tmpRet mock.Arguments
	if len(mode) > 0 {
		tmpRet = _mock.Called(space, index, offset, limit, iterator, key, mode)
	} else {
		tmpRet = _mock.Called(space, index, offset, limit, iterator, key)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SelectAsync")
	}

	var r0 *tarantool.Future
	if returnFunc, ok := ret.Get(0).(func(interface{}, interface{}, uint32, uint32, tarantool.Iter, interface{}, ...pool.Mode) *tarantool.Future); ok {
		r0 = returnFunc(space, index, offset, limit, iterator, key, mode...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tarantool.Future)
		}
	}
	return r0
}

// Pooler_SelectAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectAsync'
type Pooler_SelectAsync_Call struct {
	*mock.Call
}

// SelectAsync is a helper method to define mock.On call
//   - space interface{}
//   - index interface{}
//   - offset uint32
//   - limit uint32
//   - iterator tarantool.Iter
//   - key interface{}
//   - mode ...pool.Mode
func (_e *Pooler_Expecter) SelectAsync(space any, index any, offset any, limit any, iterator any, key any, mode ...any) *Pooler_SelectAsync_Call {
	return &Pooler_SelectAsync_Call{Call: _e.mock.On("SelectAsync",
		append([]any{space, index, offset, limit, iterator, key}, mode...)...)}
}

func (_c *Pooler_SelectAsync_Call) Run(run func(space interface{}, index interface{}, offset uint32, limit uint32, iterator tarantool.Iter, key interface{}, mode ...pool.Mode)) *Pooler_SelectAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 uint32
		if args[2] != nil {
			arg2 = args[2].(uint32)
		}
		var arg3 uint32
		if args[3] != nil {
			arg3 = args[3].(uint32)
		}
		var arg4 tarantool.Iter
		if args[4] != nil {
			arg4 = args[4].(tarantool.Iter)
		}
		var arg5 interface{}
		if args[5] != nil {
			arg5 = args[5].(interface{})
		}
		var arg6 []pool.Mode
		var variadicArgs []pool.Mode
		if len(args) > 6 {
			variadicArgs = args[6].([]pool.Mode)
		}
		arg6 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6...,
		)
	})
	return _c
}

func (_c *Pooler_SelectAsync_Call) Return(future *tarantool.Future) *Pooler_SelectAsync_Call {
	_c.Call.Return(future)
	return _c
}

func (_c *Pooler_SelectAsync_Call) RunAndReturn(run func(space interface{}, index interface{}, offset uint32, limit uint32, iterator tarantool.Iter, key interface{}, mode ...pool.Mode) *tarantool.Future) *Pooler_SelectAsync_Call {
	_c.Call.Return(run)
	return _c
}

// SelectTyped provides a mock function for the type Pooler
func (_mock *Pooler) SelectTyped(space interface{}, index interface{}, offset uint32, limit uint32, iterator tarantool.Iter, key interface{}, result interface{}, mode ...pool.Mode) error {
	var tmpRet mock.Arguments
	if len(mode) > 0 {
		tmpRet = _mock.Called(space, index, offset, limit, iterator, key, result, mode)
	} else {
		tmpRet = _mock.Called(space, index, offset, limit, iterator, key, result)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SelectTyped")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(interface{}, interface{}, uint32, uint32, tarantool.Iter, interface{}, interface{}, ...pool.Mode) error); ok {
		r0 = returnFunc(space, index, offset, limit, iterator, key, result, mode...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Pooler_SelectTyped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectTyped'
type Pooler_SelectTyped_Call struct {
	*mock.Call
}

// SelectTyped is a helper method to define mock.On call
//   - space interface{}
//   - index interface{}
//   - offset uint32
//   - limit uint32
//   - iterator tarantool.Iter
//   - key interface{}
//   - result interface{}
//   - mode ...pool.Mode
func (_e *Pooler_Expecter) SelectTyped(space any, index any, offset any, limit any, iterator any, key any, result any, mode ...any) *Pooler_SelectTyped_Call {
	return &Pooler_SelectTyped_Call{Call: _e.mock.On("SelectTyped",
		append([]any{space, index, offset, limit, iterator, key, result}, mode...)...)}
}

func (_c *Pooler_SelectTyped_Call) Run(run func(space interface{}, index interface{}, offset uint32, limit uint32, iterator tarantool.Iter, key interface{}, result interface{}, mode ...pool.Mode)) *Pooler_SelectTyped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 uint32
		if args[2] != nil {
			arg2 = args[2].(uint32)
		}
		var arg3 uint32
		if args[3] != nil {
			arg3 = args[3].(uint32)
		}
		var arg4 tarantool.Iter
		if args[4] != nil {
			arg4 = args[4].(tarantool.Iter)
		}
		var arg5 interface{}
		if args[5] != nil {
			arg5 = args[5].(interface{})
		}
		var arg6 interface{}
		if args[6] != nil {
			arg6 = args[6].(interface{})
		}
		var arg7 []pool.Mode
		var variadicArgs []pool.Mode
		if len(args) > 7 {
			variadicArgs = args[7].([]pool.Mode)
		}
		arg7 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7...,
		)
	})
	return _c
}

func (_c *Pooler_SelectTyped_Call) Return(err error) *Pooler_SelectTyped_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Pooler_SelectTyped_Call) RunAndReturn(run func(space interface{}, index interface{}, offset uint32, limit uint32, iterator tarantool.Iter, key interface{}, result interface{}, mode ...pool.Mode) error) *Pooler_SelectTyped_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type Pooler
func (_mock *Pooler) Update(space interface{}, index interface{}, key interface{}, ops *tarantool.Operations, mode ...pool.Mode) ([]interface{}, error) {
	var tmpRet mock.Arguments
	if len(mode) > 0 {
		tmpRet = _mock.Called(space, index, key, ops, mode)
	} else {
		tmpRet = _mock.Called(space, index, key, ops)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 []interface{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(interface{}, interface{}, interface{}, *tarantool.Operations, ...pool.Mode) ([]interface{}, error)); ok {
		return returnFunc(space, index, key, ops, mode...)
	}
	if returnFunc, ok := ret.Get(0).(func(interface{}, interface{}, interface{}, *tarantool.Operations, ...pool.Mode) []interface{}); ok {
		r0 = returnFunc(space, index, key, ops, mode...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(interface{}, interface{}, interface{}, *tarantool.Operations, ...pool.Mode) error); ok {
		r1 = returnFunc(space, index, key, ops, mode...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Pooler_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Pooler_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - space interface{}
//   - index interface{}
//   - key interface{}
//   - ops *tarantool.Operations
//   - mode ...pool.Mode
func (_e *Pooler_Expecter) Update(space any, index any, key any, ops any, mode ...any) *Pooler_Update_Call {
	return &Pooler_Update_Call{Call: _e.mock.On("Update",
		append([]any{space, index, key, ops}, mode...)...)}
}

func (_c *Pooler_Update_Call) Run(run func(space interface{}, index interface{}, key interface{}, ops *tarantool.Operations, mode ...pool.Mode)) *Pooler_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 *tarantool.Operations
		if args[3] != nil {
			arg3 = args[3].(*tarantool.Operations)
		}
		var arg4 []pool.Mode
		var variadicArgs []pool.Mode
		if len(args) > 4 {
			variadicArgs = args[4].([]pool.Mode)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *Pooler_Update_Call) Return(ifaceVals []interface{}, err error) *Pooler_Update_Call {
	_c.Call.Return(ifaceVals, err)
	return _c
}

func (_c *Pooler_Update_Call) RunAndReturn(run func(space interface{}, index interface{}, key interface{}, ops *tarantool.Operations, mode ...pool.Mode) ([]interface{}, error)) *Pooler_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAsync provides a mock function for the type Pooler
func (_mock *Pooler) UpdateAsync(space interface{}, index interface{}, key interface{}, ops *tarantool.Operations, mode ...pool.Mode) *tarantool.Future {
	var tmpRet mock.Arguments
	if len(mode) > 0 {
		tmpRet = _mock.Called(space, index, key, ops, mode)
	} else {
		tmpRet = _mock.Called(space, index, key, ops)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateAsync")
	}

	var r0 *tarantool.Future
	if returnFunc, ok := ret.Get(0).(func(interface{}, interface{}, interface{}, *tarantool.Operations, ...pool.Mode) *tarantool.Future); ok {
		r0 = returnFunc(space, index, key, ops, mode...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tarantool.Future)
		}
	}
	return r0
}

// Pooler_UpdateAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAsync'
type Pooler_UpdateAsync_Call struct {
	*mock.Call
}

// UpdateAsync is a helper method to define mock.On call
//   - space interface{}
//   - index interface{}
//   - key interface{}
//   - ops *tarantool.Operations
//   - mode ...pool.Mode
func (_e *Pooler_Expecter) UpdateAsync(space any, index any, key any, ops any, mode ...any) *Pooler_UpdateAsync_Call {
	return &Pooler_UpdateAsync_Call{Call: _e.mock.On("UpdateAsync",
		append([]any{space, index, key, ops}, mode...)...)}
}

func (_c *Pooler_UpdateAsync_Call) Run(run func(space interface{}, index interface{}, key interface{}, ops *tarantool.Operations, mode ...pool.Mode)) *Pooler_UpdateAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 *tarantool.Operations
		if args[3] != nil {
			arg3 = args[3].(*tarantool.Operations)
		}
		var arg4 []pool.Mode
		var variadicArgs []pool.Mode
		if len(args) > 4 {
			variadicArgs = args[4].([]pool.Mode)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *Pooler_UpdateAsync_Call) Return(future *tarantool.Future) *Pooler_UpdateAsync_Call {
	_c.Call.Return(future)
	return _c
}

func (_c *Pooler_UpdateAsync_Call) RunAndReturn(run func(space interface{}, index interface{}, key interface{}, ops *tarantool.Operations, mode ...pool.Mode) *tarantool.Future) *Pooler_UpdateAsync_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTyped provides a mock function for the type Pooler
func (_mock *Pooler) UpdateTyped(space interface{}, index interface{}, key interface{}, ops *tarantool.Operations, result interface{}, mode ...pool.Mode) error {
	var tmpRet mock.Arguments
	if len(mode) > 0 {
		tmpRet = _mock.Called(space, index, key, ops, result, mode)
	} else {
		tmpRet = _mock.Called(space, index, key, ops, result)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateTyped")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(interface{}, interface{}, interface{}, *tarantool.Operations, interface{}, ...pool.Mode) error); ok {
		r0 = returnFunc(space, index, key, ops, result, mode...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Pooler_UpdateTyped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTyped'
type Pooler_UpdateTyped_Call struct {
	*mock.Call
}

// UpdateTyped is a helper method to define mock.On call
//   - space interface{}
//   - index interface{}
//   - key interface{}
//   - ops *tarantool.Operations
//   - result interface{}
//   - mode ...pool.Mode
func (_e *Pooler_Expecter) UpdateTyped(space any, index any, key any, ops any, result any, mode ...any) *Pooler_UpdateTyped_Call {
	return &Pooler_UpdateTyped_Call{Call: _e.mock.On("UpdateTyped",
		append([]any{space, index, key, ops, result}, mode...)...)}
}

func (_c *Pooler_UpdateTyped_Call) Run(run func(space interface{}, index interface{}, key interface{}, ops *tarantool.Operations, result interface{}, mode ...pool.Mode)) *Pooler_UpdateTyped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 *tarantool.Operations
		if args[3] != nil {
			arg3 = args[3].(*tarantool.Operations)
		}
		var arg4 interface{}
		if args[4] != nil {
			arg4 = args[4].(interface{})
		}
		var arg5 []pool.Mode
		var variadicArgs []pool.Mode
		if len(args) > 5 {
			variadicArgs = args[5].([]pool.Mode)
		}
		arg5 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5...,
		)
	})
	return _c
}

func (_c *Pooler_UpdateTyped_Call) Return(err error) *Pooler_UpdateTyped_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Pooler_UpdateTyped_Call) RunAndReturn(run func(space interface{}, index interface{}, key interface{}, ops *tarantool.Operations, result interface{}, mode ...pool.Mode) error) *Pooler_UpdateTyped_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type Pooler
func (_mock *Pooler) Upsert(space interface{}, tuple interface{}, ops *tarantool.Operations, mode ...pool.Mode) ([]interface{}, error) {
	var tmpRet mock.Arguments
	if len(mode) > 0 {
		tmpRet = _mock.Called(space, tuple, ops, mode)
	} else {
		tmpRet = _mock.Called(space, tuple, ops)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 []interface{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(interface{}, interface{}, *tarantool.Operations, ...pool.Mode) ([]interface{}, error)); ok {
		return returnFunc(space, tuple, ops, mode...)
	}
	if returnFunc, ok := ret.Get(0).(func(interface{}, interface{}, *tarantool.Operations, ...pool.Mode) []interface{}); ok {
		r0 = returnFunc(space, tuple, ops, mode...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(interface{}, interface{}, *tarantool.Operations, ...pool.Mode) error); ok {
		r1 = returnFunc(space, tuple, ops, mode...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Pooler_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type Pooler_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - space interface{}
//   - tuple interface{}
//   - ops *tarantool.Operations
//   - mode ...pool.Mode
func (_e *Pooler_Expecter) Upsert(space any, tuple any, ops any, mode ...any) *Pooler_Upsert_Call {
	return &Pooler_Upsert_Call{Call: _e.mock.On("Upsert",
		append([]any{space, tuple, ops}, mode...)...)}
}

func (_c *Pooler_Upsert_Call) Run(run func(space interface{}, tuple interface{}, ops *tarantool.Operations, mode ...pool.Mode)) *Pooler_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 *tarantool.Operations
		if args[2] != nil {
			arg2 = args[2].(*tarantool.Operations)
		}
		var arg3 []pool.Mode
		var variadicArgs []pool.Mode
		if len(args) > 3 {
			variadicArgs = args[3].([]pool.Mode)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *Pooler_Upsert_Call) Return(ifaceVals []interface{}, err error) *Pooler_Upsert_Call {
	_c.Call.Return(ifaceVals, err)
	return _c
}

func (_c *Pooler_Upsert_Call) RunAndReturn(run func(space interface{}, tuple interface{}, ops *tarantool.Operations, mode ...pool.Mode) ([]interface{}, error)) *Pooler_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertAsync provides a mock function for the type Pooler
func (_mock *Pooler) UpsertAsync(space interface{}, tuple interface{}, ops *tarantool.Operations, mode ...pool.Mode) *tarantool.Future {
	var tmpRet mock.Arguments
	if len(mode) > 0 {
		tmpRet = _mock.Called(space, tuple, ops, mode)
	} else {
		tmpRet = _mock.Called(space, tuple, ops)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpsertAsync")
	}

	var r0 *tarantool.Future
	if returnFunc, ok := ret.Get(0).(func(interface{}, interface{}, *tarantool.Operations, ...pool.Mode) *tarantool.Future); ok {
		r0 = returnFunc(space, tuple, ops, mode...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tarantool.Future)
		}
	}
	return r0
}

// Pooler_UpsertAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertAsync'
type Pooler_UpsertAsync_Call struct {
	*mock.Call
}

// UpsertAsync is a helper method to define mock.On call
//   - space interface{}
//   - tuple interface{}
//   - ops *tarantool.Operations
//   - mode ...pool.Mode
func (_e *Pooler_Expecter) UpsertAsync(space any, tuple any, ops any, mode ...any) *Pooler_UpsertAsync_Call {
	return &Pooler_UpsertAsync_Call{Call: _e.mock.On("UpsertAsync",
		append([]any{space, tuple, ops}, mode...)...)}
}

func (_c *Pooler_UpsertAsync_Call) Run(run func(space interface{}, tuple interface{}, ops *tarantool.Operations, mode ...pool.Mode)) *Pooler_UpsertAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 *tarantool.Operations
		if args[2] != nil {
			arg2 = args[2].(*tarantool.Operations)
		}
		var arg3 []pool.Mode
		var variadicArgs []pool.Mode
		if len(args) > 3 {
			variadicArgs = args[3].([]pool.Mode)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *Pooler_UpsertAsync_Call) Return(future *tarantool.Future) *Pooler_UpsertAsync_Call {
	_c.Call.Return(future)
	return _c
}

func (_c *Pooler_UpsertAsync_Call) RunAndReturn(run func(space interface{}, tuple interface{}, ops *tarantool.Operations, mode ...pool.Mode) *tarantool.Future) *Pooler_UpsertAsync_Call {
	_c.Call.Return(run)
	return _c
}
