name: Run checks

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Tarantool
        uses: tarantool/setup-tarantool@v4
        with:
          tarantool-version: '2.11'

      - name: Setup tt
        run: |
          curl -L https://tarantool.io/release/2/installer.sh | sudo bash
          sudo apt install -y tt
          tt version

      - name: Setup luacheck
        run: tt rocks install luacheck 0.25.0

      - name: Run luacheck
        run: ./.rocks/bin/luacheck .

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          args: --config=.golangci.yaml
